emacs-open: new options

diff --git a/bin/emacs-open b/bin/emacs-open
--- a/bin/emacs-open
+++ b/bin/emacs-open
@@ -6,6 +6,65 @@ export PATH="$PATH:/Applications/Emacs.app/Contents/MacOS/bin"
 
 export EMACS_PLUS_NO_PATH_INJECTION=1
 
+print_usage() {
+	echo "Usage: $0 [-c|-f|--create-frame|--[new-]frame] [-t|--[new-]tab] [-v|--verbose] [--] [file...]"
+	echo "   or: $0 [-v|--verbose] -n|--new [emacs_args...]"
+}
+
+# read options
+verbose=
+create_frame=
+create_tab=
+new_emacs=
+while [[ $# -gt 0 ]]; do
+	case "$1" in
+		(--version|-V)
+			echo "emacs-open 0.0.1-pre"
+			exit
+			;;
+		(--help|-h|-H)
+			print_usage
+			exit 0
+			;;
+		(-c|--create-frame|-f|--new-frame|--frame)
+			create_frame=1
+			shift
+			;;
+		(-t|--new-tab|--tab)
+			create_tab=1
+			shift
+			;;
+		(-n|--new)
+			new_emacs=1
+			shift
+			break # so that the rest of the flags (e.g., --profile) will go through to emacs
+			;;
+		(--verbose|-v)
+			verbose=1
+			shift
+			;;
+		(--)
+			shift
+			break
+			;;
+		(-[^-][^-]*) # expand multiple single-char options (e.g. -vf)
+			opt="$1"
+			shift
+			other="${opt#-?}"
+			set -- "${opt%"$other"}" "-${other}" "$@"
+			;;
+		(-*)
+			echo "ERROR: Unknown option: $1"
+			print_usage
+			exit 1
+			;;
+		(*)
+			break
+			;;
+	esac
+done
+
+# see if pipe is needed
 needs_pipe=
 if (( $# == 0 )) && [[ ! -t 0 ]] && [[ -t 2 ]]; then
 	# No args, stdin isn't a tty but stderr is -> something is probably being piped to us
@@ -15,7 +74,14 @@ args=()
 for arg in "$@"; do
 	case "$arg" in
 		-)
-			needs_pipe=1
+			if [[ -n "$create_frame" ]] || [[ -n "$new_emacs" ]]; then
+				DIR=$(mktemp -d "$TMPDIR/epipe-$$.XXXXXXXXXX")
+				out="$DIR/pipe"
+				( umask 077; cat >"$out"; )
+				args+=("$out")
+			else
+				needs_pipe=1
+			fi
 			;;
 		*)
 			args+=("$arg")
@@ -24,8 +90,16 @@ for arg in "$@"; do
 done
 set -- "${args[@]}"
 
+if [[ -n "$verbose" ]]; then
+	set -x
+fi
+
+if [[ -n "$create_tab" ]]; then
+	emacsclient -e '(tab-new)'
+fi
+
 if [ -n "$INSIDE_EMACS" ]; then
-	emacsclient -n "$@"
+	emacsclient -n -- "$@"
 else
 	# Use this when you want a file to be open in Emacs
 	# (Or you just want to open Emacs)
@@ -34,35 +108,45 @@ else
 	# If Emacs is already running, open the file in the existing Emacs.
 	# Don't wait for it to finish.
 
-	if [ -n "$EMACS_MAC" ]; then
-		if [ $# -eq 0 ]; then
+	if [[ -n "$EMACS_MAC" ]]; then
+		if [[ $# -eq 0 ]]; then
 			# number of args is zero
 			open /Applications/Emacs.app
-		elif pgrep -f Emacs.app >/dev/null; then
+		elif [[ -z "$new_emacs" ]] && pgrep -f Emacs.app >/dev/null; then
 			# emacs server/daemon is already running
 			open /Applications/Emacs.app & # focus Emacs
-			emacsclient -n "$@"
+			emacsclient -n -- "$@"
 		else
 			# emacs server/daemon is not running
 			open /Applications/Emacs.app --args "$@"
 		fi
+	elif [[ -n "$new_emacs" ]]; then
+		nohup emacs "$@" </dev/null >/dev/null 2>&1 &
 	else
 		emacs-daemon-wait
 		# open /Applications/Emacs.app & # focus Emacs
-		if [ "$(emacsclient -e '(display-graphic-p)')" = "t" ]; then
-			for arg in "$@"; do
-				emacsclient -n "$arg"
-			done
-			emacsclient -e '(akn/focus-this-frame)' >/dev/null
-		else
-			if [ "$(uname -s)" = "Linux" ]; then
-				# For some reason, emacsclient -c -n wasn't working on my Asahi Linux
-				TERM=xterm-256color nohup emacsclient -c "$@" </dev/null >/dev/null 2>&1 &
-			else
-				TERM=xterm-256color emacsclient -c -n "$@"
+		if [[ "$(emacsclient -e '(display-graphic-p)')" = "t" ]]; then
+			# first arg
+			flags=(-n)
+			if [[ -n "$create_frame" ]]; then
+				flags+=(-c)
 			fi
-			emacsclient -e '(akn/focus-this-frame)' >/dev/null
+			TERM=xterm-256color emacsclient "${flags[@]}" -- "$1"
+			shift
+			# rest of args
+			for arg in "$@"; do
+				flags=(-n)
+				TERM=xterm-256color emacsclient "${flags[@]}" -- "$arg"
+			done
+		else
+			if [[ "$(uname -s)" = "Linux" ]]; then
+				# For some reason, emacsclient -c -n wasn't working on my Asahi Linux
+				TERM=xterm-256color nohup emacsclient -c -- "$@" </dev/null >/dev/null 2>&1 &
+			else
+				TERM=xterm-256color emacsclient -c -n -- "$@"
+			fi
 		fi
+		emacsclient -e '(ignore-errors (akn/focus-this-frame))' >/dev/null
 	fi
 fi
 
